CREATE TABLE restaurants (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    name VARCHAR(255),
    avatar VARCHAR(255),
    phone VARCHAR(200),
    countryCode VARCHAR(5),
    slug VARCHAR(255),
    street VARCHAR(255),
    district VARCHAR(255),
    city VARCHAR(255),
    full_address VARCHAR(255),
    rating FLOAT,
    username VARCHAR(255),
    lat FLOAT,
    long FLOAT,
    is_opening BOOLEAN,
    is_opening_24h BOOLEAN,
    minutes_until_next_status INT,
    promoted_at TIMESTAMP,
    is_loship_partner BOOLEAN,
    is_honored BOOLEAN,
    quote TEXT,
    is_active BOOLEAN,
    is_checked_in BOOLEAN,
    closed BOOLEAN,
    recommended_ratio FLOAT,
    recommended_enable BOOLEAN,
    distance INT,
    is_purchased_supply_items BOOLEAN,
    is_sponsored BOOLEAN,
    free_shipping_milestone INT
);

